name: Reusable workflow example

on:
  workflow_call:
    inputs:
      prefix:
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=${{ inputs.prefix }}_hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=${{ inputs.prefix }}_world" >> "$GITHUB_OUTPUT"
