# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  reusable_call_job:
    name: Reusable call job
    uses: ./.github/workflows/reusable_job.yml
    with:
      prefix: aaaaaa
  test_vars:
    runs-on: ubuntu-latest
    needs: reusable_call_job
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        env:
            OUTPUT1: ${{needs.reusable_call_job/job1.outputs.output1}}
            OUTPUT2: ${{needs.reusable_call_job.outputs.output2}}
        run: |
          echo "OUTPUT1: $OUTPUT1"
          echo "OUTPUT2: $OUTPUT2"

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
