# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

env:
  PREFIX: bbbbbbb
    
jobs:
  env_vars:
    runs-on: ubuntu-latest
    outputs:
      PREFIX: ${{ steps.gen_output.outputs.prefix }}
    steps:
      - name: Generate output
        id: gen_output
        run: |
          echo "prefix=$PREFIX" >> "$GITHUB_OUTPUT"
  reusable_call_job:
    name: Reusable call job
    uses: ./.github/workflows/reusable_job.yml
    needs: env_vars
    with:
      # prefix: aaaaaa
      prefix: ${{ needs.env_vars.outputs.PREFIX }}
  test_vars:
    runs-on: ubuntu-latest
    needs: reusable_call_job
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        env:
            OUTPUT1: ${{ needs.reusable_call_job.outputs.output1 }}
            OUTPUT2: ${{ needs.reusable_call_job.outputs.output2 }}
        run: |
          echo "OUTPUT1: $OUTPUT1"
          echo "OUTPUT2: $OUTPUT2"
          echo ${{ needs.reusable_call_job.outputs.output1 }} ${{ needs.reusable_call_job.outputs.output2 }}
  generate_tag:
    runs-on: ubuntu-latest
    needs: reusable_call_job
    steps:
      - name: Create tag
        uses: actions/github-script@v7
        env:
            # OUTPUT1: 'refs/tags/${{ needs.reusable_call_job.outputs.output1 }}'
            OUTPUT1: ${{ needs.reusable_call_job.outputs.output1 }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ process.env.OUTPUT1 }},
              sha: context.sha
            })