# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

env:
  PREFIX: bbbbbbb
    
jobs:
  reusable_call_job:
    name: Reusable call job
    uses: ./.github/workflows/reusable_job.yml
    with:
      # prefix: aaaaaa
      prefix: $PREFIX
  test_vars:
    runs-on: ubuntu-latest
    needs: reusable_call_job
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        env:
            OUTPUT1: ${{ needs.reusable_call_job.outputs.output1 }}
            OUTPUT2: ${{ needs.reusable_call_job.outputs.output2 }}
        run: |
          echo "OUTPUT1: $OUTPUT1"
          echo "OUTPUT2: $OUTPUT2"
          echo ${{ needs.reusable_call_job.outputs.output1 }} ${{ needs.reusable_call_job.outputs.output2 }}